on:
  push:
    branches:
    - main
    tags:
    - '!*'
  pull_request:
    branches:
    - main

permissions: {}

name: main
jobs:
  update_github_pages:
    name: Update github pages
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint

    - name: Run build
      run: npm run build

    - name: Publish ghpages branch
      if: github.ref == 'refs/heads/main'
      run: |
        set -e
        mv dist ..
        git checkout --orphan ghpages
        git reset --hard
        rm -Rf node_modules
        cp -R ../dist/* .
        git add .
        git status
        git config --global user.name 'Dirk Lemstra'
        git config --global user.email 'dirk@lemstra.org'
        git commit -m "Updated GitHub pages"
        git push --force origin ghpages
